from operator import indexOf
import FreeCAD, FreeCADGui, Part
import math
from . import GDMLShared

class GDMLParaboloid(GDMLsolid):
    def __init__(self, obj, rlo, rhi, dz, lunit, material, colour=None):
        super().__init__(obj)
        """Add some custom properties for the Paraboloid feature"""
        obj.addProperty(
            "App::PropertyFloat", "rlo", "GDMLParaboloid", "radius at -z/2"
        ).rlo = rlo
        obj.addProperty(
            "App::PropertyFloat", "rhi", "GDMLParaboloid", "radius at +z/2"
        ).rhi = rhi
        obj.addProperty(
            "App::PropertyFloat",
            "dz",
            "GDMLParaboloid",
            "Paraboloid half length",
        ).dz = dz
        obj.addProperty(
            "App::PropertyEnumeration", "lunit", "GDMLParaboloid", "lunit"
        )
        setLengthQuantity(obj, lunit)
        obj.addProperty(
            "App::PropertyEnumeration",
            "material",
            "GDMLParaboloid",
            "Material",
        )
        setMaterial(obj, material)
        if FreeCAD.GuiUp:
            updateColour(obj, colour, material)
        # Suppress Placement - position & Rotation via parent App::Part
        # this makes Placement via Phyvol easier and allows copies etc
        self.Type = "GDMLParaboloid"
        self.colour = colour
        self.Object = obj
        obj.Proxy = self
        obj.Proxy.Type = "GDMLParaboloid"

    def onChanged(self, fp, prop):
        """Do something when a property has changed"""
        # print(fp.Label+" State : "+str(fp.State)+" prop : "+prop)
        if "Restore" in fp.State:
            return

        if prop in ["material"]:
            if FreeCAD.GuiUp:
                if hasattr(self, "colour"):
                    if self.colour is None:
                        fp.ViewObject.ShapeColor = colourMaterial(fp.material)
                if fp.material == "G4_AIR":
                    print("Set Transparency")
                    fp.ViewObject.Transparency = 98

        if prop in ["rlo", "rhi", "z", "lunit"]:
            self.createGeometry(fp)

        if prop in ["scale"]:
            self.createGeometry(fp)

    # def execute(self, fp): in GDMLsolid

    def createGeometry(self, fp):
        currPlacement = fp.Placement
        # GDMLShared.setTrace(True)
        GDMLShared.trace("Execute Hyperbolic Tube")
        # this should probably be a global variable, but
        # for now adopt the value used in geant4.10.07.p02
        NUMBER_OF_DIVISIONS = 24
        mul = GDMLShared.getMult(fp)
        rlo = mul * fp.rlo
        rhi = mul * fp.rhi
        dz = mul * fp.dz
        if dz < 0 or rlo > rhi:
            errmsg = "paraboloid: error in input parameters: dz < 0 and/or rlo > rhi"
            print(errmsg)
            print(f" rlo= {rlo} rhi= {rhi}  dz= {dz}")
            return

        # Prepare polylines
        ns = NUMBER_OF_DIVISIONS
        # paraboloid given by following equation:
        # rho^2 = k1 * z + k2, (rho = distance of point on surface from z-axis)
        # k1 and k2 can be obtained from requirement:
        # rlo^2 = k1*(-dz) + k2
        # rhi^2 = k1*(dz) + k2
        k1 = (rhi * rhi - rlo * rlo) / (2 * dz)
        k2 = (rhi * rhi + rlo * rlo) / 2
        #
        # solid generated by external hyperbeloid
        deltaz = 2 * dz / (ns - 1)
        zz = [dz - deltaz * i for i in range(0, ns)]
        rr = [math.sqrt(k1 * zi + k2) for zi in zz]
        outersolid = rotateAroundZ(NUMBER_OF_DIVISIONS, zz, rr)
        fp.Shape = outersolid
        if hasattr(fp, "scale"):
            super().scale(fp)
        fp.Placement = currPlacement
