from operator import indexOf
import FreeCAD, FreeCADGui, Part
import math
from . import GDMLShared

class GDMLHype(GDMLsolid):
    def __init__(
        self,
        obj,
        rmin,
        rmax,
        z,
        inst,
        outst,
        aunit,
        lunit,
        material,
        colour=None,
    ):
        super().__init__(obj)
        """Add some custom properties for Hyperbolic Tube feature"""
        obj.addProperty(
            "App::PropertyFloat", "rmin", "GDMLHype", "inner radius at z=0"
        ).rmin = rmin
        obj.addProperty(
            "App::PropertyFloat", "rmax", "GDMLHype", "outer radius at z=0"
        ).rmax = rmax
        obj.addProperty(
            "App::PropertyFloat", "z", "GDMLHype", "Tube length"
        ).z = z
        obj.addProperty(
            "App::PropertyFloat", "inst", "GDMLHype", "Inner stereo"
        ).inst = inst
        obj.addProperty(
            "App::PropertyFloat", "outst", "GDMLHype", "Outer stero"
        ).outst = outst
        obj.addProperty(
            "App::PropertyEnumeration", "aunit", "GDMLHype", "aunit"
        )
        setAngleQuantity(obj, aunit)
        obj.addProperty(
            "App::PropertyEnumeration", "lunit", "GDMLHype", "lunit"
        )
        setLengthQuantity(obj, lunit)
        obj.addProperty(
            "App::PropertyEnumeration", "material", "GDMLHype", "Material"
        )
        setMaterial(obj, material)
        if FreeCAD.GuiUp:
            updateColour(obj, colour, material)
        # Suppress Placement - position & Rotation via parent App::Part
        # this makes Placement via Phyvol easier and allows copies etc
        self.Type = "GDMLHype"
        self.colour = colour
        self.Object = obj
        obj.Proxy = self
        obj.Proxy.Type = "GDMLHype"

    def onChanged(self, fp, prop):
        """Do something when a property has changed"""
        # print(fp.Label+" State : "+str(fp.State)+" prop : "+prop)
        if "Restore" in fp.State:
            return

        if prop in ["material"]:
            if FreeCAD.GuiUp:
                if hasattr(self, "colour"):
                    if self.colour is None:
                        fp.ViewObject.ShapeColor = colourMaterial(fp.material)
                if fp.material == "G4_AIR":
                    print("Set Transparency")
                    fp.ViewObject.Transparency = 98

        if prop in ["rmin", "rmax", "z", "inst", "outst", "aunit", "lunit"]:
            self.createGeometry(fp)

        if prop in ["scale"]:
            self.createGeometry(fp)

    # def execute(self, fp): in GDMLsolid

    def createGeometry(self, fp):
        currPlacement = fp.Placement
        # GDMLShared.setTrace(True)
        GDMLShared.trace("Execute Hyperbolic Tube")
        # this should probably be a global variable, but
        # for now adopt the value used in geant4.10.07.p02
        NUMBER_OF_DIVISIONS = 36
        mul = GDMLShared.getMult(fp)
        rmin = mul * fp.rmin
        rmax = mul * fp.rmax
        z = mul * fp.z
        inst = getAngleRad(fp.aunit, fp.inst)
        outst = getAngleRad(fp.aunit, fp.outst)
        sqrtan1 = math.tan(inst)
        sqrtan1 *= sqrtan1
        sqrtan2 = math.tan(outst)
        sqrtan2 *= sqrtan2

        # mirroring error checking in HepPolyhedron.cc
        k = 0
        if rmin < 0.0 or rmax < 0.0 or rmin >= rmax:
            k = 1
        if z <= 0.0:
            k += 2

        if k != 0:
            errmsg = "HepPolyhedronHype: error in input parameters: "
            if (k & 1) != 0:
                errmsg += " (radii)"
            if (k & 2) != 0:
                errmsg += " (half-length)"
            print(errmsg)
            print(f" rmin= {rmin} rmax= {rmax}  z= {z}")
            return

        # Prepare two polylines
        ns = NUMBER_OF_DIVISIONS
        if ns < 3:
            ns = 3
        if sqrtan1 == 0.0:
            nz1 = 2
        else:
            nz1 = ns + 1
        if sqrtan2 == 0.0:
            nz2 = 2
        else:
            nz2 = ns + 1

        halfZ = z / 2
        #
        # solid generated by external hyperbeloid
        dz2 = z / (nz2 - 1)
        zz = [halfZ - dz2 * i for i in range(0, nz2)]
        rr = [math.sqrt(sqrtan2 * zi * zi + rmax * rmax) for zi in zz]
        outersolid = rotateAroundZ(NUMBER_OF_DIVISIONS, zz, rr)
        fp.Shape = outersolid

        if rmin != 0:
            #
            # solid generated by internal hyperbeloid
            dz1 = z / (nz1 - 1)
            zz = [halfZ - dz1 * i for i in range(0, nz1)]
            rr = [math.sqrt(sqrtan1 * zi * zi + rmin * rmin) for zi in zz]
            innersolid = rotateAroundZ(NUMBER_OF_DIVISIONS, zz, rr)
            fp.Shape = outersolid.cut(innersolid)
        if hasattr(fp, "scale"):
            super().scale(fp)
        fp.Placement = currPlacement
